from stuff_model import model
from refine import model as refine
from prompts import prompts
from langchain import PromptTemplate
from langchain.chat_models import ChatOpenAI
from langchain.chains import LLMChain
from langchain.output_parsers import PydanticOutputParser
from langchain.pydantic_v1 import BaseModel, Field
import time
import pandas as pd


def summary_validation(
    doc,
    summary_prompt=prompts.basic_summary_prompt,
    model_base_name="gpt-4o-mini",
):
    start_time = time.time()
    llm = ChatOpenAI(temperature=0, model_name=model_base_name)

    base_response_output_key = "base_response"
    base_response_chain = refine.refine_model(
        doc=doc, prompt=summary_prompt, model_name=model_base_name
    )

    query = (
        summary_prompt
        + f"""

        Now summarize the next article: 
        
        {doc}
    """
    )

    class PlanVerificationsOutput(BaseModel):
        query: str = Field(description="The user's query")
        base_response: str = Field(description="The response to the user's query")
        facts_and_verification_questions: dict[str, str] = Field(
            description="Facts (as the dictionary keys) extracted from the response and verification questions related to the query (as the dictionary values)"
        )

    plan_verifications_output_parser = PydanticOutputParser(
        pydantic_object=PlanVerificationsOutput
    )

    plan_verifications_template = """
    Given the below Question and answer, generate a series of verification questions that test the factual claims in the original baseline response.
    For example if part of a longform model response contains the statement “The Mexican–American War
    was an armed conflict between the United States and Mexico from 1846 to 1848”, then one possible
    verification question to check those dates could be “When did the Mexican American war start and
    end?”

    # Question: {query}
    # Answer: {base_response}

    # <fact in passage>, <verification question, generated by combining the query and the fact>

    # {format_instructions}
    # """

    plan_verifications_prompt_template = PromptTemplate(
        input_variables=[query] + [base_response_output_key],
        template=plan_verifications_template,
        partial_variables={
            "format_instructions": plan_verifications_output_parser.get_format_instructions()
        },
    )

    plan_verifications_chain = LLMChain(
        llm=llm,
        prompt=plan_verifications_prompt_template,
        output_key="output",
        output_parser=plan_verifications_output_parser,
    )

    plan = plan_verifications_chain.invoke(
        {"query": query, "base_response": base_response_chain[0]}
    )

    intermediate_result = plan["output"]

    claimed_facts = list(intermediate_result.facts_and_verification_questions.keys())
    verification_questions = list(
        intermediate_result.facts_and_verification_questions.values()
    )

    verify_input_variables = ["article", "question", "answer"]
    verify_output_key = "answer"

    verify_template = """

    Next I will give you a news article Article: 

    Article: {article}

    Now using only the information in the article, I will provide you with a question and its answer, and you must return True if the answer is correct or False if the answer is false or the article does not contain enough information to answer the question.


    Question: {question}


    Answer: {answer}

    """

    verify_prompt_template = PromptTemplate(
        input_variables=verify_input_variables, template=verify_template
    )

    verify_chain = LLMChain(
        llm=llm,
        prompt=verify_prompt_template,
        output_key=verify_output_key,
    )

    answer = []
    for i in range(len(verification_questions)):
        answer.append(
            verify_chain.invoke(
                {
                    "article": doc,
                    "question": verification_questions[i],
                    "answer": claimed_facts[i],
                }
            )["answer"]
        )
    end_time = time.time()  # End timing
    execution_time = end_time - start_time  # Calculate total execution time
    resume = base_response_chain[0]
    pd.DataFrame(
        {
            "Question": verification_questions,
            "Answer": claimed_facts,
            "Agent Review": answer,
        }
    ).to_csv(
        "validations.csv",
        index=False,
    )
    return answer, verification_questions, claimed_facts, execution_time


if __name__ == "__main__":
    summary_validation(
        doc="""
JERUSALEM (AP) — An Israeli ground offensive in the Gaza Strip would further escalate the war raging since Hamas launched its unprecedented attack, killing hundreds of civilians. A ground invasion also would threaten to draw in the Iranian-backed Lebanese militant group Hezbollah from the north. The United States has deployed one aircraft carrier group to the region, with another on the way later this week — reflecting concerns of a widening conflict and meant to establish a force that deters Iran and others.   It would be the the third major ground assault in Gaza since Israel left the seaside enclave in 2005.   Here's what is known about the weapons of those who would be involved.   ISRAEL  Israel's military has long been supported by the United States, with $3.3 billion in congressionally mandated annual funding, plus another $500 million toward missile defense technology.  Israel is one of the best-armed nations in the wider Middle East. Its air force includes the advanced American F-35 fighter jet, missile defense batteries including the American-made Patriot, and the Iron Dome missile defense system.  Israel has armored personnel carriers and tanks, and a fleet of drones and other technology available to support any street-to-street battles. Israel trains soldiers on such techniques at its Urban Warfare Training Center, known colloquially as “Mini Gaza.”  Israel has some 170,000 troops typically on active duty and has called up some 360,000 reservists for the war — three-fourths of its estimated capacity, according to the International Institute for Strategic Studies.   Israel has also long maintained an undeclared nuclear weapons program.   HAMAS    Hamas, the rulers of the Gaza Strip since 2007, do not have the billions of dollars in aid and advanced weaponry of the Israeli military. But the surprise weekend attack included militants on paragliders and grenade-dropping drones, and Hamas can leverage guerrilla warfare tactics that could make any ground assault dangerous for Israeli troops.   Hamas has 15,000 to 20,000 fighters, the International Institute for Strategic Studies estimates. Israel puts the number higher, at up to 30,000 fighters.   The Hamas arsenal includes assault rifles, heavy machine guns, rocket-propelled grenades and anti-tank weapons, as well as longer-range sniper rifles. In the past, Hamas has employed boobytraps and suicide bombers.   Though Israel has a vast missile defense network, Hamas has created a vast supply of locally manufactured missiles with the aim of firing multiple salvos to break through. The Israeli military says over 5,000 missiles have been fired toward the country since the war began. Israeli intelligence in 2021 estimated Hamas and Islamic Jihad, another militant group operating in Gaza, had some 30,000 missiles in their arsenal. Analysts say there are no signs, yet, that Hamas has developed guided missiles, which can more precisely strike at targets.   HEZBOLLAH  The Iranian-backed Lebanese militant group Hezbollah sits just across Israel's northern border. Since Hamas’ attack, there have been limited exchanges of fire between Hezbollah and Israel, but no wide-scale offensive. But the forces Hezbollah could bring remain a concern for Israel.   Hezbollah's leader, Hassan Nasrallah, had boasted that the group has 100,000 fighters, though other estimates put its troop strength at less than half that.   Hezbollah holds a vast arsenal “mostly of small, man-portable and unguided surface-to-surface artillery rockets,” according to the Center for Strategic and International Studies. The U.S. has estimated Hezbollah and other militant groups in Lebanon have some 150,000 missiles and rockets. Hezbollah also has been working on precision-guided missiles.   Hezbollah has previously launched drones into Israel. Its forces also have assault rifles, heavy machine guns, rocket-propelled grenades, roadside bombs and other weaponry.   THE UNITED STATES   The U.S. military has sent the aircraft carrier USS Gerald R. Ford and its battle group to the eastern Mediterranean to provide air support if needed to Israel with its surveillance aircraft and F-18 fighter jets.   Meanwhile, the USS Dwight D. Eisenhower carrier strike group will leave its homeport of Norfolk, Virginia, and sail for the Mediterranean, potentially doubling the Navy’s Israel response.   The U.S. military also maintains a vast network of bases across the wider Middle East. However, because Israel's punishing airstrike campaign on the Gaza Strip has inflamed anger among Muslims in the wider region, the U.S. will likely be asked not to fly any potential air missions out of those nations. That would force the Pentagon to rely on carrier-based launches to provide any support to Israel it may need.
""",
        summary_prompt=prompts.summary_prompt_without_zero_shot,
        model_base_name="gpt-4o",
    )
